apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gloo
  namespace: gloo-system
spec:
  chart:
    repository: https://storage.googleapis.com/solo-public-helm
    name: gloo
    version: 1.3.26
  values:
    gatewayProxies:
      gatewayProxy:
        service:
          extraAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
