#!/usr/bin/env bash
#
# Bootstraps Flux and Helm operator on a Kubernetes cluster.

set -e

GIT_ROOT_DIR="$(git rev-parse --show-toplevel)"

# Deploy Flux to the cluster using Kustomize.
kubectl apply -k "${GIT_ROOT_DIR}/base/flux"

# Wait for Flux to start.
kubectl -n flux rollout status deployment/flux

# Deploy Helm operator to the cluster using Kustomize.
kustomize build "${GIT_ROOT_DIR}/base/helm-operator" | kubectl apply -f -

# Wait for Helm operator to start.
kubectl -n flux rollout status deployment/helm-operator

# Setup GitHub write access for Flux.
FLUX_KEY="$(fluxctl identity --k8s-fwd-ns flux)"

current_context="$(kubectl config current-context)"
cluster="${current_context#*@}"
github_access_token="$(cat ${HOME}/github_access_token)"
# Remove deploy key if it already exists.

curl \
 -i \
 -u ecrews:$github_access_token  \
 --data @- https://api.github.com/repos/ecrews/gitops-demo-fluxcd/keys << EOF
{
    "title" : "flux-${cluster}",
    "key" : "${FLUX_KEY}",
    "read_only" : false
}
EOF
