apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --memcached-hostname=memcached.flux
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-branch=playground
            - --git-path=cluster
            - --git-poll-interval=30s
            - --sync-interval=30s
            - --sync-garbage-collection=true
            - --git-user=ecrews
            - --git-email=ecrews@users.noreply.github.com
            - --git-url=git@github.com:ecrews/gitops-demo-fluxcd
